apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEPLOYMENT_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{DEPLOYMENT_NAME}}
    version: {{VERSION}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{DEPLOYMENT_NAME}}
  template:
    metadata:
      labels:
        app: {{DEPLOYMENT_NAME}}
        version: {{VERSION}}
    spec:
      imagePullSecrets:
      - name: {{IMAGE_PULL_SECRET}}
      containers:
      - name: {{CONTAINER_NAME}}
        image: {{IMAGE}}
        ports:
        - containerPort: {{PORT}}
          protocol: TCP
        resources:
          limits:
            cpu: {{RESOURCE_LIMITS_CPU}}
            memory: {{RESOURCE_LIMITS_MEMORY}}
          requests:
            cpu: {{RESOURCE_REQUESTS_CPU}}
            memory: {{RESOURCE_REQUESTS_MEMORY}}
        env:
        {{ENV_VARS}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{DEPLOYMENT_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{DEPLOYMENT_NAME}}
spec:
  type: {{SERVICE_TYPE}}
  selector:
    app: {{DEPLOYMENT_NAME}}
  ports:
  - port: {{PORT}}
    targetPort: {{PORT}}
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{DEPLOYMENT_NAME}}
  namespace: {{NAMESPACE}}
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    {{INGRESS_ANNOTATIONS}}
spec:
  tls:
  - hosts:
    - {{INGRESS_HOST}}
    secretName: {{INGRESS_SECRET}}
  rules:
  - host: {{INGRESS_HOST}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{DEPLOYMENT_NAME}}
            port:
              number: {{PORT}}
